### ISSUE TITLE
Send customer email after they buy with confirmation and links for tracking and email address to contact us

### ISSUE THREAD

**Issue by haffi96** [bilal-and-haffi/ai-print-shop#90]
https://resend.com/docs/send-with-nextjs

- [ ] email service (resend.com/ mailgun / sendgrid or something else)
- [ ] email template
- [ ] link to printify connect
- [ ] link to a website /order/view page which can only be click through the emails

**Comment by Bilalm354** [comment]
https://developers.printify.com/#orders

<img width="871" alt="image" src="https://github.com/bilal-and-haffi/aiPersonalisedGifts/assets/53113053/517b3ed4-4222-426c-9d6d-f35457f5416d">

Might be handled by printify like this

**Comment by haffi96** [comment]
> https://developers.printify.com/#orders
> 
> <img width="871" alt="image" src="https://github.com/bilal-and-haffi/aiPersonalisedGifts/assets/53113053/517b3ed4-4222-426c-9d6d-f35457f5416d">
> 
> Might be handled by printify like this

That's email to us or customer?

**Comment by Bilalm354** [comment]
I thought it mean customer

**Comment by Bilalm354** [comment]
you were right. it doesn't mean customer

**Comment by Bilalm354** [comment]
https://vercel.com/guides/sending-emails-from-an-application-on-vercel

https://postmarkapp.com/pricing
